In [23]:
## Association Rule Mining

In [ ]:
'''
     Aturan asosiasi (Association Rule) adalah metode data mining untuk mencari suatu hubungan yang menunjukkan kondisi di dalam 
satu set data, yang beberapa nilai atribut akan muncul secara bersamaan(Sofyan 2019). Aturan ini juga digunakan untuk menemukan
aturan asosiatif antara suatu kombinasi item atau hubungan suatu data yang digunakan untuk memprediksi suatu pola (Maulidah dan
Bachtiar 2021). Metode ini dianggap sebagai metode data mining yang tidak bergantung pada hipotesis apa pun dan dapat menemukan 
koneksi bermakna yang tersembunyi dalam kumpulan data besar.

     Association Rule ini umumnya mencari IF-Then yang sering dan berpola. Ada beberapa hal yang digunakan untuk mengukur 
sekumpulan items ini sering muncul bersamaan atau tidak (Amelia, 2021). Pentingnya aturan asosiasi dapat ditentukan oleh dua 
parameter, yaitu minimum support (presentase kombinasi item dalam database) dan minimum confidence (hubungan yang kuat antara 
item dalam aturan asosiasi), keduanya ditentukan oleh penggunanya (Fauzy, Saleh W, and Asror 2016).

     Dalam aturan ini, terdapat suatu interestingness measure (ukuran kepercayaan) yang diperoleh dari hasil pengolahan data 
dengan perhitungan tertentu digunakan untuk menentukan aturan asosiasi. Pada umumnya terdapat tiga ukuran (Rerung 2018), yaitu :
1) Support : yaitu suatu ukuran yang menunjukkan seberapa besar tingkat dominasi suatu item/itemset dari keseluruhan data yang 
diobservasi. Ukuran ini akan menentukan apakah suatu item/itemset layak untuk dicari confidence-nya (contohnya, dari seluruh 
transaksi sebuah toko, seberapa besar tingkat dominasi yang menunjukkan bahwa item A dan B dibeli secara bersamaan) dapat juga 
digunakan untuk mencari tingkat dominasi item tunggal. Secara umum dapat ditulis seperti persamaan berikut : 
Support (A→B) = Probabilitas (A→B)

2) Confidence: yaitu suatu ukuran yang menunjukkan hubungan antar dua item secara conditional (misal, seberapa sering item B 
dibeli jika orang membeli item A). Secara umum dapat ditulis seperti persamaan berikut :
Confidence (A→B) = Support (A→B) / Support A

3) Improvement/Lift: yaitu suatu ukuran yang menunjukan besarnya kemungkinan dua item dapat dibeli secara bersamaan. Lebih jelasnya 
dapat dilihat pada persamaan berikut :
Improvement (A→B) = Support (A→B) / Support(A) x Support(B)

      Ketiga ukuran ini berguna untuk membandingkan dengan threshold/batasan yang ditentukan. Batasan biasanya ditentukan dari 
min_support, min_confidence, dan min_improvement. Algoritma yang biasanya digunakan dalam Association Rule sebagai berikut :
1) Algoritma Apriori
   Algoritma apriori menggunakan pengetahuan frekuensi atribut yang telah diketahui sebelumnya untuk memproses informasi 
selanjutnya. Pada algoritma apriori menentukan kandidat yang mungkin muncul dengan cara memperhatikan minimum support dan
minimum confidence. Support (nilai penunjang) adalah persentasi kombinasi item tersebut dalam database, untuk menghitung nilai 
support pada sebuah item diperoleh dengan menggunakan persamaan (Nola Ritha, Suswaini, and Pebriadi 2021).
2) Algoritma AIS
   kumpulan item dibuat dan dihitung saat memindai data. Dalam data transaksi, algoritma AIS menentukan kumpulan item besar 
manakah yang berisi transaksi, dan kumpulan item kandidat baru dibuat dengan memperluas kumpulan item besar dengan item lain 
dalam data transaksi (Lutkevich, 2020).
3)Algoritma SETM
  Algotima ini menghasilkan kumpulan item kandidat saat memindai database, tetapi algoritme ini memperhitungkan kumpulan item 
di akhir pemindaiannya. Itemset kandidat baru dihasilkan dengan cara yang sama seperti algoritma AIS, tetapi ID transaksi dari 
transaksi yang dihasilkan disimpan dengan itemset kandidat dalam struktur data berurutan. Di akhir, jumlah dukungan kandidat 
itemset dibuat dengan menggabungkan struktur berurutan (Lutkevich, 2020).

    Penerapan implementasi dari Association Rule sebegai berikut :
1) Market-Basket Analysis
   Market basket analysis adalah suatu metode analisa atas perilaku konsumen secara spesifik dari suatu golongan / kelompok 
tertentu. Sumber data dari market basket analysis antara lain dapat bersumber dari transaksi kartu kredit, kartu lotere, kupon 
diskon, panggilan keluhan pelanggan (Gunadi and Sensuse 2012).
2) Diagnosis Medis
   Aturan asosiasi dalam diagnosis medis dapat membantu dokter mendiagnosis penyakit pasien. Diagnosis adalah proses yang sulit 
dengan banyak kesalahan potensial yang dapat menyebabkan hasil yang tidak dapat diandalkan. Penambangan aturan asosiasi 
relasional diperlukan untuk menentukan penyakit berdasarkan faktor dan gejalanya (Jena, 2022) .
3) Data Sensus
   Konsep Association Rule Mining juga digunakan dalam menangani jumlah data sensus yang sangat besar. Jika diselaraskan dengan 
benar, informasi ini dapat digunakan dalam merencanakan layanan publik dan bisnis yang efisien  (Jena, 2022).
4) Banking Service
   Digunakan oleh pengguna ritel (rekening industri uang, CD, layanan investasi, pinjaman mobil, dll.) Dengan tujuan mengenali 
pengguna yang mungkin membutuhkan layanan lain (Ginni, 2022).
       

"""

In [35]:
# install mlextend library
pip install mlxtend

Collecting mlxtend
  Downloading mlxtend-0.21.0-py2.py3-none-any.whl (1.3 MB)
Collecting scikit-learn>=1.0.2
  Downloading scikit_learn-1.1.3-cp38-cp38-win_amd64.whl (7.5 MB)
Requirement already satisfied: setuptools in c:\users\asus\anaconda3\lib\site-packages (from mlxtend) (52.0.0.post20210125)
Requirement already satisfied: joblib>=0.13.2 in c:\users\asus\anaconda3\lib\site-packages (from mlxtend) (1.0.1)
Requirement already satisfied: numpy>=1.16.2 in c:\users\asus\anaconda3\lib\site-packages (from mlxtend) (1.20.1)
Requirement already satisfied: scipy>=1.2.1 in c:\users\asus\anaconda3\lib\site-packages (from mlxtend) (1.6.2)
Requirement already satisfied: matplotlib>=3.0.0 in c:\users\asus\anaconda3\lib\site-packages (from mlxtend) (3.3.4)
Requirement already satisfied: pandas>=0.24.2 in c:\users\asus\anaconda3\lib\site-packages (from mlxtend) (1.2.4)
Requirement already satisfied: cycler>=0.10 in c:\users\asus\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in c:\users\asus\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.4.7)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\asus\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.8.1)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\asus\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.3.1)
Requirement already satisfied: pillow>=6.2.0 in c:\users\asus\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (8.2.0)
Requirement already satisfied: six in c:\users\asus\anaconda3\lib\site-packages (from cycler>=0.10->matplotlib>=3.0.0->mlxtend) (1.15.0)
Requirement already satisfied: pytz>=2017.3 in c:\users\asus\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2021.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\asus\anaconda3\lib\site-packages (from scikit-learn>=1.0.2->mlxtend) (2.1.0)
Installing collected packages: scikit-learn, mlxtend
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 0.24.1
    Uninstalling scikit-learn-0.24.1:
      Successfully uninstalled scikit-learn-0.24.1
Successfully installed mlxtend-0.21.0 scikit-learn-1.1.3
Note: you may need to restart the kernel to use updated packages.

In [36]:
#Import Library
import pandas as pd
import numpy as np
from mlxtend.frequent_patterns import apriori, association_rules

In [45]:
df = pd.read_csv('https://raw.githubusercontent.com/baghizzhd/Data-Mining-association_rule_mining/main/retail_dataset.csv', sep=',')
df.head()

C:\Users\Asus\anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

        0       1     2       3       4       5       6
0   Bread    Wine  Eggs    Meat  Cheese  Pencil  Diaper
1   Bread  Cheese  Meat  Diaper    Wine    Milk  Pencil
2  Cheese    Meat  Eggs    Milk    Wine     NaN     NaN
3  Cheese    Meat  Eggs    Milk    Wine     NaN     NaN
4    Meat  Pencil  Wine     NaN     NaN     NaN     NaN

In [46]:
# kita periksa ukuran dataset kita
df.shape

C:\Users\Asus\anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

(315, 7)

In [47]:
#Data Prepocessing
items = (df['0'].unique())
items

C:\Users\Asus\anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

array(['Bread', 'Cheese', 'Meat', 'Eggs', 'Wine', 'Bagel', 'Pencil',
       'Diaper', 'Milk'], dtype=object)

In [48]:
# Metode One-Hot Encoding digunakan untuk membantu kita melakukan ini
encoded_vals = []
for index, row in df.iterrows(): 
    labels = {}
    uncommons = list(set(items) - set(row))
    commons = list(set(items).intersection(row))
    for uc in uncommons:
        labels[uc] = 0
    for com in commons:
        labels[com] = 1
    encoded_vals.append(labels)

C:\Users\Asus\anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [50]:
df2 = pd.DataFrame(encoded_vals)

C:\Users\Asus\anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [51]:
#Mari kita lihat apa yang terjadi setelah dilakukannya One-Hot Encoding
df2

C:\Users\Asus\anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

     Bagel  Milk  Pencil  Cheese  Meat  Diaper  Wine  Eggs  Bread
0        0     0       1       1     1       1     1     1      1
1        0     1       1       1     1       1     1     0      1
2        0     1       0       1     1       0     1     1      0
3        0     1       0       1     1       0     1     1      0
4        0     0       1       0     1       0     1     0      0
..     ...   ...     ...     ...   ...     ...   ...   ...    ...
310      0     0       0       1     0       0     0     1      1
311      0     1       1       0     1       0     0     0      0
312      0     0       1       1     1       1     1     1      1
313      0     0       0       1     1       0     0     0      0
314      1     0       0       0     1       0     1     1      1

[315 rows x 9 columns]

In [52]:
#Association Rules
'''Untuk apriori, perlu melakukannya dengan memberikan df2 dengan hot encoding yang telah dilakukan. 
Saya akan mencoba menggunakan parameter dukungan minimum untuk pemodelan ini. Untuk ini, saya menetapkan nilai min_support 
dengan nilai ambang 20%'''

freq_items = apriori(df2, min_support = 0.2, use_colnames = True, verbose = 1)

Processing 4 combinations | Sampling itemset size 4

C:\Users\Asus\anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
C:\Users\Asus\anaconda3\lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:111: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

In [53]:
#Dengan demikian, nilai support akan dihitung. Mari kita periksa
freq_items.head()

C:\Users\Asus\anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

    support  itemsets
0  0.425397   (Bagel)
1  0.501587    (Milk)
2  0.361905  (Pencil)
3  0.501587  (Cheese)
4  0.476190    (Meat)

In [54]:
#Terakhir, kita akan melihat fungsi association_rules, kita perlu menggunakan support (item frekuensi)
#Saya memilih nilai confidence minimum 60%. Dengan kata lain, ketika produk X dibeli, kita dapat mengatakan bahwa pembelian produk Y adalah 60% atau lebih.
association_rules(freq_items, metric = "confidence", min_threshold = 0.6)

C:\Users\Asus\anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Bagel),(Bread),0.425397,0.504762,0.279365,0.656716,1.301042,0.064641,1.442650
1,(Cheese),(Milk),0.501587,0.501587,0.304762,0.607595,1.211344,0.053172,1.270148
2,(Milk),(Cheese),0.501587,0.501587,0.304762,0.607595,1.211344,0.053172,1.270148
3,(Cheese),(Meat),0.501587,0.476190,0.323810,0.645570,1.355696,0.084958,1.477891
4,(Meat),(Cheese),0.476190,0.501587,0.323810,0.680000,1.355696,0.084958,1.557540
5,(Wine),(Cheese),0.438095,0.501587,0.269841,0.615942,1.227986,0.050098,1.297754
6,(Eggs),(Cheese),0.438095,0.501587,0.298413,0.681159,1.358008,0.078670,1.563203
7,(Eggs),(Meat),0.438095,0.476190,0.266667,0.608696,1.278261,0.058050,1.338624
8,"(Cheese, Meat)",(Milk),0.323810,0.501587,0.203175,0.627451,1.250931,0.040756,1.337845
9,"(Cheese, Milk)",(Meat),0.304762,0.476190,0.203175,0.666667,1.400000,0.058050,1.571429
10,"(Meat, Milk)",(Cheese),0.244444,0.501587,0.203175,0.831169,1.657077,0.080564,2.952137
11,"(Cheese, Meat)",(Eggs),0.323810,0.438095,0.215873,0.666667,1.521739,0.074014,1.685714
12,"(Cheese, Eggs)",(Meat),0.298413,0.476190,0.215873,0.723404,1.519149,0.073772,1.893773
13,"(Meat, Eggs)",(Cheese),0.266667,0.501587,0.215873,0.809524,1.613924,0.082116,2.616667

In [ ]:
#Kita dapat dengan mudah melihat seberapa sering ada hubungan antara produk mana.
Misalnya, jika kita memeriksa nilai indeks pertama kita atau 1 :
1. Probabilitas melihat penjualan keju dilihat sebagai 50%.
2. Susu dilihat sebagai 50%.
3. Kita dapat mengatakan bahwa dukungan dari keduanya diukur sebagai 30%.
4. 60% dari mereka yang membeli keju, membeli susu juga.
5. Korelasi mereka satu sama lain terlihat sebagai 1,27.
6. Akibatnya, jika barang X dan Y lebih sering dibeli bersama, maka beberapa langkah dapat diambil untuk meningkatkan keuntungan.

In [ ]:
Akibatnya, jika barang X dan Y lebih sering dibeli bersamaan, maka beberapa langkah dapat diambil untuk meningkatkan keuntungan. 
Contohnya:
1. Cross-Selling dapat ditingkatkan dengan menggabungkan produk – barang
2. Tata letak toko dapat diubah sehingga penjualan dapat ditingkatkan saat item tertentu disimpan bersama.
3. Kegiatan promosi yang merupakan kampanye periklanan dapat dilakukan untuk meningkatkan penjualan barang yang tidak dibeli
   pelanggan.
4. Diskon kolektif dapat ditawarkan pada produk ini jika pelanggan membeli keduanya.

In [ ]:
#Daftar Pustaka
'''
Fauzy, Mohamad, Kemas Rahmat Saleh W, and Ibnu Asror. 2016. “Penerapan Metode Association Rule Menggunakan Algoritma Apriori Pada Simulasi Prediksi Hujan Wilayah Kota Bandung.” Jurnal Ilmiah Teknologi Infomasi Terapan 2(3). doi: 10.33197/jitter.vol2.iss3.2016.111.
    
Sofyan. 2019. “Implementation of Data Mining with Association Rule in Decision Making for Product Purchase Correlation Using the Apriori Algorithm.” Journal of Chemical Information and Modeling 53(9):1689–99.

Asosiasi Ulasan Terhadap Aspek Tempat Wisata Jawa Timur Park 3 Application of Association Rule Mining Method for Association of Reviews on Aspect in Tourist Attraction Jawa Timur Park 3.” 8(5):1029–38. doi: 10.25126/jtiik.202184417.

Rerung, Rintho Rante. 2018. “Penerapan Data Mining Dengan Memanfaatkan Metode Association Rule Untuk Promosi Produk.” Jurnal Teknologi Rekayasa 3(1):89. doi: 10.31544/jtera.v3.i1.2018.89-98.
        
Nola Ritha, Eka Suswaini, and Wisnu Pebriadi. 2021. “Penerapan Association Rule Menggunakan Algoritma Apriori Pada Poliklinik Penyakit Dalam (Studi Kasus: Rumah Sakit Umum Daerah Bintan).” Jurnal Sains Dan Informatika 7(2):222–30. doi: 10.34128/jsi.v7i2.329.

Gunadi, Goldie, and Dana Indra Sensuse. 2012. “Penerapan Metode Data Mining Market Basket Analysis Terhadap Data Penjualan Produk Buku Dengan Menggunakan Algoritma Apriori Dan Frequent Pattern Growth ( Fp-Growth ) :” Telematika 4(1):118–32.

AKTURK, M. (2020). Association Rules on Business Problem. Retrieved from Kaggle: https://www.kaggle.com/code/mathchi/association-rules-on-business-problem
        
Amelia, S. S. (2021, October 29). Metode Data Mining : Association. Retrieved from Binus: https://sis.binus.ac.id/2021/10/29/metode-data-mining-association/
            
Ginni. (2022, February 15). What are the applications of Association Rule? Retrieved from tutorialspoint: https://www.tutorialspoint.com/what-are-the-applications-of-association-rule
        
Jena, M. (2022, May 27). Association Rule Mining Simplified 101. Retrieved from Hevodata: https://hevodata.com/learn/association-rule-mining/
        
Lutkevich, B. (2020, September). association rules definition. Retrieved from techtarget: https://www.techtarget.com/searchbusinessanalytics/definition/association-rules-in-data-mining
'''